# Define base image of seaweedfs
x-seaweedfs: &seaweedfs
  image: chrislusf/seaweedfs:latest
  restart: unless-stopped
  networks:
    - internal

# Define base configurations using YAML anchors
x-master-base: &master-base
  <<: *seaweedfs
  volumes:
    - /data
  healthcheck: &master-healthcheck
    test: ["CMD", "wget", "--spider", "-q", "http://localhost:9333/cluster/status"]
    interval: 10s
    timeout: 5s
    retries: 3
    start_period: 10s

x-volume-base: &volume-base
  <<: *seaweedfs
  volumes:
    - /data
  depends_on:
    master1:
      condition: service_healthy
    master2:
      condition: service_healthy
    master3:
      condition: service_healthy
  healthcheck: &volume-healthcheck
    test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/status"]
    interval: 10s
    timeout: 5s
    retries: 3
    start_period: 10s

x-filer-base: &filer-base
  <<: *seaweedfs
  depends_on:
    master1:
      condition: service_healthy
    master2:
      condition: service_healthy
    master3:
      condition: service_healthy
    volume1:
      condition: service_healthy
    volume2:
      condition: service_healthy
    volume3:
      condition: service_healthy
  deploy:
    resources:
      limits:
        cpus: '1'
        memory: 1G
  volumes:
    - /data
  command: "filer -master=master1:9333,master2:9333,master3:9333 -ip=0.0.0.0 -port=8888 -dataCenter=dc1 -maxMB=1024"
  healthcheck: &filer-healthcheck
    test: ["CMD", "wget", "--spider", "-q", "http://localhost:8888/"]
    interval: 10s
    timeout: 5s
    retries: 3
    start_period: 15s
    
# New: S3 Gateway base configuration
x-s3-base: &s3-base
  <<: *seaweedfs
  volumes:
    - ./s3.toml:/s3.toml
  depends_on:
    filer:
      condition: service_healthy
  deploy:
    resources:
      limits:
        cpus: '0.5'
        memory: 512M
  command: "s3 -filer=filer:8888 -ip.bind=0.0.0.0 -port=8333"
  healthcheck: &s3-healthcheck
    test: ["CMD", "sh", "-c", "netstat -tlnp | grep :8333"]
    interval: 10s
    timeout: 5s
    retries: 3
    start_period: 10s

services:
  # Master servers using base configuration
  master1:
    <<: *master-base
    container_name: master1
    command: "master -port=9333 -ip=master1 -mdir=/data -peers=master1:9333,master2:9333,master3:9333"
    volumes:
      - master1_data:/data
    healthcheck:
      <<: *master-healthcheck
      test: ["CMD", "wget", "--spider", "-q", "http://master1:9333/cluster/status"]

  master2:
    <<: *master-base
    container_name: master2
    command: "master -port=9333 -ip=master2 -mdir=/data -peers=master1:9333,master2:9333,master3:9333"
    volumes:
      - master2_data:/data
    healthcheck:
      <<: *master-healthcheck
      test: ["CMD", "wget", "--spider", "-q", "http://master2:9333/cluster/status"]

  master3:
    <<: *master-base
    container_name: master3
    command: "master -port=9333 -ip=master3 -mdir=/data -peers=master1:9333,master2:9333,master3:9333"
    volumes:
      - master3_data:/data
    healthcheck:
      <<: *master-healthcheck
      test: ["CMD", "wget", "--spider", "-q", "http://master3:9333/cluster/status"]

  # Volume servers using base configuration
  volume1:
    <<: *volume-base
    container_name: volume1
    command: "volume -port=8080 -ip=volume1 -mserver=master1:9333,master2:9333,master3:9333 -dir=/data -max=5 -rack=rack1"
    volumes:
      - volume1_data:/data
    healthcheck:
      <<: *volume-healthcheck
      test: ["CMD", "wget", "--spider", "-q", "http://volume1:8080/status"]

  volume2:
    <<: *volume-base
    container_name: volume2
    command: "volume -port=8080 -ip=volume2 -mserver=master1:9333,master2:9333,master3:9333 -dir=/data -max=5 -rack=rack2"
    volumes:
      - volume2_data:/data
    healthcheck:
      <<: *volume-healthcheck
      test: ["CMD", "wget", "--spider", "-q", "http://volume2:8080/status"]

  volume3:
    <<: *volume-base
    container_name: volume3
    command: "volume -port=8080 -ip=volume3 -mserver=master1:9333,master2:9333,master3:9333 -dir=/data -max=5 -rack=rack3"
    volumes:
      - volume3_data:/data
    healthcheck:
      <<: *volume-healthcheck
      test: ["CMD", "wget", "--spider", "-q", "http://volume3:8080/status"]

  # Filer server
  filer:
    <<: *filer-base
    container_name: filer
    volumes:
      - filer_data:/data

  # S3 Gateway server
  s3:
    <<: *s3-base
    container_name: s3

  # API server (no changes needed)
  api:
    build:
      context: api
      args:
        DOCKER_GID: ${DOCKER_GID}
    container_name: api
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_S3_ADDRESSING_STYLE: ${AWS_S3_ADDRESSING_STYLE}
      SEAWEED_S3_URL: http://s3:8333
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Proxy server (no changes needed)
  proxy:
    build: proxy
    container_name: proxy
    ports:
      - "80:80"
      - "8888:8888"
      - "8333:8333"
    volumes:
      - ./.htpasswd:/etc/nginx/.htpasswd
    networks:
      - internal
      - external
    depends_on:
      master1:
        condition: service_healthy
      master2:
        condition: service_healthy
      master3:
        condition: service_healthy
      volume1:
        condition: service_healthy
      volume2:
        condition: service_healthy
      volume3:
        condition: service_healthy
      filer:
        condition: service_healthy
      s3:
        condition: service_healthy
      api:
        condition: service_healthy

networks:
  external:
    name: external
  internal:
    name: internal

volumes:
  master1_data:
  master2_data:
  master3_data:
  volume1_data:
  volume2_data:
  volume3_data:
  filer_data:
